# This file was generated by GoReleaser. DO NOT EDIT.
cask "mycel" do
  version "0.2.11"

  on_macos do
    on_intel do
      sha256 "3e7d4095b0101127f1b0c96ed55371e04323ecdca69b0bdbb556b310e6d34690"
      url "https://github.com/mycelpf/mycel_cli/releases/download/v#{version}/mycel_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f55a97309d2bc9ab0f1407bd9b3fd4ebadac1b34ef3377179b2af61d95748778"
      url "https://github.com/mycelpf/mycel_cli/releases/download/v#{version}/mycel_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4cc2b6b2343fd12a9655d68352566c67291e206cbfc8ddfa35d76e81450d01b5"
      url "https://github.com/mycelpf/mycel_cli/releases/download/v#{version}/mycel_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f21a72250be0a75e0b1f8e1012cdc69965b2729efbbd6ac2f5104a42a70c5df5"
      url "https://github.com/mycelpf/mycel_cli/releases/download/v#{version}/mycel_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mycel"
  desc "mycel — the umbrella CLI for the mycel_* family (app-builder)"
  homepage "https://github.com/mycelpf/mycel_cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mycel"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mycel"]
  end

  # No zap stanza required

  caveats <<~EOS
    mycel is ad-hoc signed, not Apple-notarized. This cask clears the download
    quarantine automatically. If macOS still blocks it on first run
    ("mycel cannot be opened because Apple cannot check it for malicious software"),
    allow it once with:
      xattr -dr com.apple.quarantine "$(brew --prefix)/bin/mycel"
    or approve it under System Settings -> Privacy & Security -> Open Anyway.
  EOS
end
