# This file was generated by GoReleaser. DO NOT EDIT.
cask "mycel" do
  version "0.3.44"

  on_macos do
    on_arm do
      sha256 "0e60eb55e5f515f0b437ff31c90c0257390858d202e7e474551cf9b575bf5461"
      url "https://github.com/mycelpf/mycel_cli/releases/download/v#{version}/mycel_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cd68a60e631f34610ce5e3aea1bd90802362eca76f88d52ef460e309bb0dab5c"
      url "https://github.com/mycelpf/mycel_cli/releases/download/v#{version}/mycel_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7009339112b37f74db78805dd41d8f393264aa7d33d835219955831358077014"
      url "https://github.com/mycelpf/mycel_cli/releases/download/v#{version}/mycel_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b9d0c32e4e0b56fee9ea86f6987c5249e291841c17e08fdee50cc6e4713b1e02"
      url "https://github.com/mycelpf/mycel_cli/releases/download/v#{version}/mycel_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mycel"
  desc "mycel — the umbrella CLI for the mycel_* family (app-builder)"
  homepage "https://github.com/mycelpf/mycel_cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mycel"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mycel"]
    # Restart every REGISTERED carto daemon. This must iterate the registry, not live
    # processes: `brew upgrade --cask` uninstalls before it installs, so the
    # uninstall.launchctl above has ALREADY unloaded every agent by the time this
    # runs. A "restart what is running" implementation would find nothing, no-op, and
    # leave a clean upgrade with a dead daemon. `carto start --all` reads the registry,
    # which is why it is the right command here.
    #
    # Failure is swallowed on purpose: a daemon that did not come back is not worth
    # failing `brew install` over, and a non-zero postflight aborts or warns the whole
    # operation. `carto start --all` still reports honestly when run by hand.
    system_command "/bin/sh", args: ["-c", "'#{staged_path}/mycel' carto start --all >/dev/null 2>&1 || true"]
  end

  uninstall launchctl: [
      "com.cogniworks.mycel.carto.*",
    ]

  zap trash: [
      "~/.config/mycel/carto",
      "~/Library/Logs/mycel-carto-*.log",
    ]

  caveats <<~EOS
    mycel is ad-hoc signed, not Apple-notarized. This cask clears the download
    quarantine automatically. If macOS still blocks it on first run
    ("mycel cannot be opened because Apple cannot check it for malicious software"),
    allow it once with:
      xattr -dr com.apple.quarantine "$(brew --prefix)/bin/mycel"
    or approve it under System Settings -> Privacy & Security -> Open Anyway.
  EOS
end
